#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
// error_reporting(E_ALL); ini_set('display_errors', 1);
require(__DIR__ . '/bootstrap.php');
\ant\base\Bootstrap::run(\ant\base\Bootstrap::CONSOLE, YII_PROJECT_BASE_PATH, YII_APP_BASE_PATH);